use std::fmt;
use std::fs;
use std::io::{Cursor, Write};
use std::path::{Path, PathBuf};

use adm_new_foundation::{AdmError, AdmResult, sha256_hex};
use image::{GenericImageView, ImageFormat};
use serde_json::{Value, json};

use crate::work_units::{
    WorkUnitExecutionResult, WorkUnitExecutionStatus, WorkUnitExecutor, WorkUnitJournalRecord,
    WorkUnitReconcileDecision, WorkUnitRequest,
};

const MAX_PROVIDER_IMAGE_BYTES: usize = 32 * 1024 * 1024;
const MAX_PROVIDER_IMAGE_EDGE: u32 = 8_192;
const MAX_PROVIDER_IMAGE_PIXELS: u64 = 16 * 1024 * 1024;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StyleImageStatus {
    Generated,
    Unavailable,
    Failed,
}

#[derive(Clone, PartialEq, Eq)]
pub struct StyleImageRequest {
    pub unit_id: String,
    pub style_id: String,
    pub prompt: String,
    pub project_label: String,
    pub requested_width: u32,
    pub requested_height: u32,
    pub output_format: String,
}

impl fmt::Debug for StyleImageRequest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("StyleImageRequest")
            .field("unit_id", &self.unit_id)
            .field("style_id", &self.style_id)
            .field("prompt_chars", &self.prompt.chars().count())
            .field("project_label", &self.project_label)
            .field("requested_width", &self.requested_width)
            .field("requested_height", &self.requested_height)
            .field("output_format", &self.output_format)
            .finish()
    }
}

#[derive(Clone, PartialEq, Eq)]
pub struct StyleImageResult {
    pub status: StyleImageStatus,
    pub bytes: Option<Vec<u8>>,
    pub provider: String,
    pub model: String,
    pub width: u32,
    pub height: u32,
    pub format: String,
    pub reason_code: String,
    pub safe_message: String,
}

impl StyleImageResult {
    pub fn generated(
        bytes: Vec<u8>,
        provider: impl Into<String>,
        model: impl Into<String>,
        width: u32,
        height: u32,
    ) -> Self {
        Self {
            status: StyleImageStatus::Generated,
            bytes: Some(bytes),
            provider: provider.into(),
            model: model.into(),
            width,
            height,
            format: "png".to_string(),
            reason_code: String::new(),
            safe_message: String::new(),
        }
    }

    pub fn unavailable(code: impl Into<String>, message: impl Into<String>) -> Self {
        Self {
            status: StyleImageStatus::Unavailable,
            bytes: None,
            provider: String::new(),
            model: String::new(),
            width: 0,
            height: 0,
            format: "png".to_string(),
            reason_code: code.into(),
            safe_message: message.into(),
        }
    }

    pub fn validate_generated(&self) -> AdmResult<&[u8]> {
        if self.status != StyleImageStatus::Generated {
            return Err(AdmError::new("style image result is not generated"));
        }
        let bytes = self
            .bytes
            .as_deref()
            .ok_or_else(|| AdmError::new("generated style image has no bytes"))?;
        if self.width <= 1 || self.height <= 1 || !self.format.eq_ignore_ascii_case("png") {
            return Err(AdmError::new(
                "generated style image metadata is invalid or placeholder-sized",
            ));
        }
        Ok(bytes)
    }
}

impl fmt::Debug for StyleImageResult {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("StyleImageResult")
            .field("status", &self.status)
            .field("byte_len", &self.bytes.as_ref().map(Vec::len))
            .field("provider", &self.provider)
            .field("model", &self.model)
            .field("width", &self.width)
            .field("height", &self.height)
            .field("format", &self.format)
            .field("reason_code", &self.reason_code)
            .field("safe_message", &self.safe_message)
            .finish()
    }
}

pub trait StyleImageGenerator: Send + Sync + fmt::Debug {
    fn execution_scope_fingerprint(&self) -> String {
        "style-image-generator-v1".to_string()
    }

    fn generate(&self, request: &StyleImageRequest) -> AdmResult<StyleImageResult>;
}

/// Executes one Step07 provider request behind the generic safe-unit journal.
///
/// The journal only receives hashes and provider metadata. The prompt stays in
/// the in-memory request payload and generated bytes are written to the private
/// cache root, never serialized as Base64 or an absolute path.
pub(crate) struct SafeStyleImageExecutor<'a> {
    generator: Option<&'a dyn StyleImageGenerator>,
    cache_root: PathBuf,
    enabled: bool,
    scope: String,
}

impl<'a> SafeStyleImageExecutor<'a> {
    pub(crate) fn new(
        generator: Option<&'a dyn StyleImageGenerator>,
        cache_root: impl AsRef<Path>,
        enabled: bool,
    ) -> Self {
        let cache_root = cache_root.as_ref().to_path_buf();
        let generator_scope = generator
            .map(StyleImageGenerator::execution_scope_fingerprint)
            .unwrap_or_else(|| "unavailable-style-image-generator-v1".to_string());
        let scope = sha256_hex(
            format!(
                "step07-style-image-safe-unit-v1|{enabled}|{generator_scope}|{}",
                cache_root.to_string_lossy()
            )
            .as_bytes(),
        );
        Self {
            generator,
            cache_root,
            enabled,
            scope,
        }
    }

    pub(crate) fn cached_png(
        &self,
        request: &WorkUnitRequest,
        result: &WorkUnitExecutionResult,
    ) -> AdmResult<Vec<u8>> {
        cached_style_png(&self.cache_root, &request.idempotency_key, result)
    }

    fn request(&self, request: &WorkUnitRequest) -> AdmResult<StyleImageRequest> {
        let string = |key: &str| {
            request
                .payload
                .get(key)
                .and_then(Value::as_str)
                .map(str::to_string)
                .ok_or_else(|| AdmError::new(format!("style image work unit is missing {key}")))
        };
        let dimension = |key: &str| {
            request
                .payload
                .get(key)
                .and_then(Value::as_u64)
                .and_then(|value| u32::try_from(value).ok())
                .filter(|value| *value > 1)
                .ok_or_else(|| AdmError::new(format!("style image work unit has invalid {key}")))
        };
        Ok(StyleImageRequest {
            unit_id: request.unit_id.clone(),
            style_id: string("style_id")?,
            prompt: string("prompt")?,
            project_label: string("project_label")?,
            requested_width: dimension("requested_width")?,
            requested_height: dimension("requested_height")?,
            output_format: string("output_format")?,
        })
    }

    fn cache_key(&self, request: &WorkUnitRequest) -> String {
        style_image_cache_key(&request.idempotency_key)
    }

    fn cache_path(&self, cache_key: &str) -> PathBuf {
        self.cache_root.join(format!("{cache_key}.png"))
    }

    fn write_cache(&self, cache_key: &str, bytes: &[u8]) -> AdmResult<()> {
        fs::create_dir_all(&self.cache_root)?;
        let final_path = self.cache_path(cache_key);
        let temp_path = self
            .cache_root
            .join(format!(".{cache_key}.{}.tmp", std::process::id()));
        {
            let mut file = fs::File::create(&temp_path)?;
            file.write_all(bytes)?;
            file.sync_all()?;
        }
        if final_path.exists() {
            fs::remove_file(&final_path)?;
        }
        if let Err(error) = fs::rename(&temp_path, &final_path) {
            let _ = fs::remove_file(&temp_path);
            return Err(AdmError::new(format!(
                "failed to commit style image cache: {error}"
            )));
        }
        Ok(())
    }

    fn failed_result(
        &self,
        status: WorkUnitExecutionStatus,
        result: Option<&StyleImageResult>,
        code: &str,
        message: &str,
    ) -> WorkUnitExecutionResult {
        WorkUnitExecutionResult {
            status,
            output_refs: Vec::new(),
            changed_files: Vec::new(),
            verification_results: Vec::new(),
            data: json!({
                "reason_code": safe_metadata(code, 80),
                "provider": result.map(|value| safe_metadata(&value.provider, 80)).unwrap_or_default(),
                "model": result.map(|value| safe_metadata(&value.model, 120)).unwrap_or_default(),
            }),
            message: safe_style_message(message),
        }
    }
}

pub(crate) fn style_image_cache_key(idempotency_key: &str) -> String {
    sha256_hex(format!("style-image-cache-v1:{idempotency_key}").as_bytes())
}

fn cached_style_png(
    cache_root: &Path,
    idempotency_key: &str,
    result: &WorkUnitExecutionResult,
) -> AdmResult<Vec<u8>> {
    if result.status != WorkUnitExecutionStatus::Verified {
        return Err(AdmError::new("style image work unit is not verified"));
    }
    let expected_key = style_image_cache_key(idempotency_key);
    let recorded_key = result
        .data
        .get("cache_key")
        .and_then(Value::as_str)
        .unwrap_or_default();
    let recorded_hash = result
        .data
        .get("content_sha256")
        .and_then(Value::as_str)
        .unwrap_or_default();
    if recorded_key != expected_key || recorded_hash.len() != 64 {
        return Err(AdmError::new(
            "style image cache metadata cannot be verified",
        ));
    }
    let bytes = fs::read(cache_root.join(format!("{expected_key}.png")))?;
    if sha256_hex(&bytes) != recorded_hash {
        return Err(AdmError::new("style image cache content hash mismatch"));
    }
    let (normalized, width, height) = normalize_png_bytes(&bytes)?;
    let recorded_width = result
        .data
        .get("width")
        .and_then(Value::as_u64)
        .unwrap_or_default();
    let recorded_height = result
        .data
        .get("height")
        .and_then(Value::as_u64)
        .unwrap_or_default();
    if u64::from(width) != recorded_width
        || u64::from(height) != recorded_height
        || normalized != bytes
    {
        return Err(AdmError::new(
            "style image cache dimensions or normalized content changed",
        ));
    }
    Ok(bytes)
}

pub(crate) fn reconcile_unbound_style_image_record(
    cache_root: &Path,
    record: &WorkUnitJournalRecord,
) -> AdmResult<WorkUnitReconcileDecision> {
    let cache_key = style_image_cache_key(&record.idempotency_key);
    let cache_path = cache_root.join(format!("{cache_key}.png"));
    let Some(result) = record.result.as_ref() else {
        return Ok(decision_for_unrecorded_cache(&cache_path));
    };
    if result.status != WorkUnitExecutionStatus::Verified {
        return Ok(decision_for_unrecorded_cache(&cache_path));
    }
    match cached_style_png(cache_root, &record.idempotency_key, result) {
        Ok(_) => Ok(WorkUnitReconcileDecision::Verified),
        Err(_) => reconcile_invalid_cache(&cache_path),
    }
}

fn decision_for_unrecorded_cache(cache_path: &Path) -> WorkUnitReconcileDecision {
    match cache_path.try_exists() {
        Ok(false) => WorkUnitReconcileDecision::SafeToRetry,
        Ok(true) | Err(_) => WorkUnitReconcileDecision::Unknown,
    }
}

fn reconcile_invalid_cache(cache_path: &Path) -> AdmResult<WorkUnitReconcileDecision> {
    match cache_path.try_exists() {
        Ok(false) => Ok(WorkUnitReconcileDecision::SafeToRetry),
        Ok(true) => match fs::remove_file(cache_path) {
            Ok(()) => Ok(WorkUnitReconcileDecision::SafeToRetry),
            Err(_) => Ok(WorkUnitReconcileDecision::Unknown),
        },
        Err(_) => Ok(WorkUnitReconcileDecision::Unknown),
    }
}

impl fmt::Debug for SafeStyleImageExecutor<'_> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("SafeStyleImageExecutor")
            .field("generator", &self.generator.is_some())
            .field("enabled", &self.enabled)
            .field(
                "cache_scope",
                &sha256_hex(self.cache_root.to_string_lossy().as_bytes()),
            )
            .finish()
    }
}

impl WorkUnitExecutor for SafeStyleImageExecutor<'_> {
    fn execution_scope_fingerprint(&self) -> String {
        self.scope.clone()
    }

    fn execute(&self, request: &WorkUnitRequest) -> AdmResult<WorkUnitExecutionResult> {
        if !self.enabled {
            return Ok(self.failed_result(
                WorkUnitExecutionStatus::Unavailable,
                None,
                "image_generation_disabled",
                "image generation is disabled",
            ));
        }
        let Some(generator) = self.generator else {
            return Ok(self.failed_result(
                WorkUnitExecutionStatus::Unavailable,
                None,
                "image_provider_unavailable",
                "no image provider was injected for this run",
            ));
        };
        let style_request = self.request(request)?;
        let result = match generator.generate(&style_request) {
            Ok(result) => result,
            Err(error) => {
                return Ok(self.failed_result(
                    WorkUnitExecutionStatus::Failed,
                    None,
                    "image_provider_failed",
                    error.message(),
                ));
            }
        };
        match result.status {
            StyleImageStatus::Generated => {
                let (bytes, width, height) = match normalize_style_image_png(&result) {
                    Ok(image) => image,
                    Err(error) => {
                        return Ok(self.failed_result(
                            WorkUnitExecutionStatus::Failed,
                            Some(&result),
                            "provider_image_invalid",
                            error.message(),
                        ));
                    }
                };
                let cache_key = self.cache_key(request);
                let content_sha256 = sha256_hex(&bytes);
                self.write_cache(&cache_key, &bytes)?;
                Ok(WorkUnitExecutionResult::verified(
                    Vec::new(),
                    Vec::new(),
                    vec![json!({
                        "id": "png_content_validation",
                        "status": "passed",
                    })],
                    json!({
                        "cache_key": cache_key,
                        "content_sha256": content_sha256,
                        "provider": safe_metadata(&result.provider, 80),
                        "model": safe_metadata(&result.model, 120),
                        "width": width,
                        "height": height,
                        "format": "png",
                    }),
                ))
            }
            StyleImageStatus::Unavailable => Ok(self.failed_result(
                WorkUnitExecutionStatus::Unavailable,
                Some(&result),
                if result.reason_code.trim().is_empty() {
                    "image_provider_unavailable"
                } else {
                    &result.reason_code
                },
                &result.safe_message,
            )),
            StyleImageStatus::Failed => Ok(self.failed_result(
                WorkUnitExecutionStatus::Failed,
                Some(&result),
                if result.reason_code.trim().is_empty() {
                    "image_provider_failed"
                } else {
                    &result.reason_code
                },
                &result.safe_message,
            )),
        }
    }

    fn reconcile(
        &self,
        request: &WorkUnitRequest,
        record: &WorkUnitJournalRecord,
    ) -> AdmResult<WorkUnitReconcileDecision> {
        let cache_key = self.cache_key(request);
        let cache_path = self.cache_path(&cache_key);
        let Some(result) = record.result.as_ref() else {
            // A crash after the cache write but before ResultReady cannot prove
            // which metadata/result should be committed. Metadata I/O failure
            // is equally ambiguous and must stay fail-closed.
            return Ok(decision_for_unrecorded_cache(&cache_path));
        };
        if result.status != WorkUnitExecutionStatus::Verified {
            return Ok(decision_for_unrecorded_cache(&cache_path));
        }
        match self.cached_png(request, result) {
            Ok(_) => Ok(WorkUnitReconcileDecision::Verified),
            Err(_) => {
                // The path is derived solely from this request lineage. A
                // corrupt cache can therefore be removed without touching an
                // unrelated side effect; failure to remove remains ambiguous.
                reconcile_invalid_cache(&cache_path)
            }
        }
    }
}

pub(crate) fn normalize_style_image_png(
    result: &StyleImageResult,
) -> AdmResult<(Vec<u8>, u32, u32)> {
    let bytes = result.validate_generated()?;
    let (normalized, width, height) = normalize_png_bytes(bytes)?;
    if width != result.width || height != result.height {
        return Err(AdmError::new(
            "generated style image dimensions are inconsistent",
        ));
    }
    Ok((normalized, width, height))
}

fn normalize_png_bytes(bytes: &[u8]) -> AdmResult<(Vec<u8>, u32, u32)> {
    if bytes.len() > MAX_PROVIDER_IMAGE_BYTES {
        return Err(AdmError::new(
            "generated style image exceeds the byte limit",
        ));
    }
    let decoded = image::load_from_memory_with_format(bytes, ImageFormat::Png)
        .map_err(|_| AdmError::new("generated style image is not a complete PNG"))?;
    let (width, height) = decoded.dimensions();
    if width <= 1
        || height <= 1
        || width > MAX_PROVIDER_IMAGE_EDGE
        || height > MAX_PROVIDER_IMAGE_EDGE
        || u64::from(width) * u64::from(height) > MAX_PROVIDER_IMAGE_PIXELS
    {
        return Err(AdmError::new(
            "generated style image dimensions are invalid",
        ));
    }
    let mut clean = Cursor::new(Vec::new());
    decoded
        .write_to(&mut clean, ImageFormat::Png)
        .map_err(|_| AdmError::new("generated style image could not be normalized"))?;
    Ok((clean.into_inner(), width, height))
}

fn safe_metadata(value: &str, max_chars: usize) -> String {
    let flattened = value.split_whitespace().collect::<Vec<_>>().join(" ");
    if sensitive_message_token(&flattened) {
        return "configured".to_string();
    }
    flattened.chars().take(max_chars).collect()
}

pub(crate) fn safe_style_message(message: &str) -> String {
    let flattened = message.split_whitespace().collect::<Vec<_>>().join(" ");
    let mut redact_next = false;
    let redacted = flattened
        .split_whitespace()
        .map(|token| {
            let label = token
                .trim_matches(|character: char| {
                    !character.is_ascii_alphanumeric() && character != '_'
                })
                .to_ascii_lowercase();
            let secret_label = matches!(
                label.as_str(),
                "bearer" | "authorization" | "api_key" | "apikey" | "access_token"
            );
            if sensitive_message_token(token) {
                redact_next = false;
                "[REDACTED]"
            } else if secret_label {
                redact_next = true;
                "[REDACTED]"
            } else if redact_next {
                redact_next = false;
                "[REDACTED]"
            } else {
                token
            }
        })
        .collect::<Vec<_>>()
        .join(" ");
    let mut safe = redacted.chars().take(240).collect::<String>();
    if flattened.chars().count() > 240 {
        safe.push('…');
    }
    safe
}

fn sensitive_message_token(token: &str) -> bool {
    let trimmed = token.trim_matches(|character: char| {
        matches!(
            character,
            '"' | '\'' | '(' | ')' | '[' | ']' | '{' | '}' | ',' | ';'
        )
    });
    let lower = trimmed.to_ascii_lowercase();
    let bytes = trimmed.as_bytes();
    let windows_absolute = bytes.len() >= 3
        && bytes[0].is_ascii_alphabetic()
        && bytes[1] == b':'
        && matches!(bytes[2], b'\\' | b'/');
    let encoded_blob = trimmed.len() >= 64
        && trimmed
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'+' | b'/' | b'='));
    let jwt = trimmed.matches('.').count() == 2
        && trimmed.split('.').all(|part| {
            part.len() >= 8
                && part
                    .bytes()
                    .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'='))
        });
    let secret_assignment = [
        "api_key=",
        "apikey=",
        "access_token=",
        "accesstoken=",
        "authorization=",
        "token=",
        "password=",
    ]
    .iter()
    .any(|prefix| lower.starts_with(prefix));
    windows_absolute
        || trimmed.starts_with('/')
        || trimmed.starts_with("\\\\")
        || lower.starts_with("file://")
        || lower.starts_with("http://")
        || lower.starts_with("https://")
        || lower.starts_with("data:image/")
        || lower.starts_with("sk-")
        || lower.starts_with("pk-")
        || lower.starts_with("ghp_")
        || secret_assignment
        || jwt
        || encoded_blob
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::work_units::{
        SafeUnitJournal, WorkUnitKind, WorkUnitRunStatus, WorkUnitStopToken,
        execute_work_unit_batch,
    };
    use adm_new_foundation::new_stable_id;
    use image::{DynamicImage, Rgb, RgbImage};
    use std::sync::Arc;
    use std::sync::atomic::{AtomicUsize, Ordering};

    #[derive(Debug)]
    struct CountingGenerator(Arc<AtomicUsize>);

    impl StyleImageGenerator for CountingGenerator {
        fn execution_scope_fingerprint(&self) -> String {
            "safe-style-image-test-v1".to_string()
        }

        fn generate(&self, request: &StyleImageRequest) -> AdmResult<StyleImageResult> {
            self.0.fetch_add(1, Ordering::AcqRel);
            let mut output = Cursor::new(Vec::new());
            DynamicImage::ImageRgb8(RgbImage::from_pixel(
                request.requested_width,
                request.requested_height,
                Rgb([24, 48, 96]),
            ))
            .write_to(&mut output, ImageFormat::Png)
            .unwrap();
            Ok(StyleImageResult::generated(
                output.into_inner(),
                "test-provider",
                "test-model",
                request.requested_width,
                request.requested_height,
            ))
        }
    }

    #[derive(Debug)]
    struct CrashAfterCache<'a>(&'a SafeStyleImageExecutor<'a>);

    impl WorkUnitExecutor for CrashAfterCache<'_> {
        fn execution_scope_fingerprint(&self) -> String {
            self.0.execution_scope_fingerprint()
        }

        fn execute(&self, request: &WorkUnitRequest) -> AdmResult<WorkUnitExecutionResult> {
            let _ = self.0.execute(request)?;
            Err(AdmError::new("injected crash after image cache commit"))
        }

        fn reconcile(
            &self,
            request: &WorkUnitRequest,
            record: &WorkUnitJournalRecord,
        ) -> AdmResult<WorkUnitReconcileDecision> {
            self.0.reconcile(request, record)
        }
    }

    #[test]
    fn cache_without_result_record_reconciles_to_recovery_blocked_without_provider_retry() {
        let root = std::env::temp_dir().join(new_stable_id("style-image-unknown-cache").unwrap());
        let cache_root = root.join("private-cache");
        let journal_root = root.join("journal");
        let calls = Arc::new(AtomicUsize::new(0));
        let generator = CountingGenerator(calls.clone());
        let executor = SafeStyleImageExecutor::new(Some(&generator), &cache_root, true);
        let crashing = CrashAfterCache(&executor);
        let journal = SafeUnitJournal::new(&journal_root);
        let stop = WorkUnitStopToken::default();
        let request = WorkUnitRequest::new(
            "07",
            "image:STYLE-01-test",
            WorkUnitKind::Art,
            json!({
                "style_id": "STYLE-01-test",
                "prompt": "secret prompt must never be serialized",
                "project_label": "private project label",
                "requested_width": 8,
                "requested_height": 8,
                "output_format": "png",
            }),
        )
        .unwrap();

        let interrupted =
            execute_work_unit_batch(vec![request.clone()], Some(&crashing), &journal, &stop)
                .unwrap();
        assert!(interrupted.recovery_blocked);
        assert_eq!(
            interrupted.units[0].status,
            WorkUnitRunStatus::RecoveryBlocked
        );
        assert_eq!(calls.load(Ordering::Acquire), 1);
        assert_eq!(fs::read_dir(&cache_root).unwrap().count(), 1);

        let reconciled =
            execute_work_unit_batch(vec![request], Some(&executor), &journal, &stop).unwrap();
        assert!(reconciled.recovery_blocked);
        assert_eq!(
            reconciled.units[0].status,
            WorkUnitRunStatus::RecoveryBlocked
        );
        assert_eq!(calls.load(Ordering::Acquire), 1);

        let journal_text = fs::read_dir(&journal_root)
            .unwrap()
            .filter_map(Result::ok)
            .flat_map(|lineage| fs::read_dir(lineage.path()).unwrap().filter_map(Result::ok))
            .map(|entry| fs::read_to_string(entry.path()).unwrap())
            .collect::<String>();
        assert!(!journal_text.contains("secret prompt"));
        assert!(!journal_text.contains("private project label"));
        assert!(!journal_text.contains("iVBOR"));
        assert!(!journal_text.contains(&root.to_string_lossy().to_string()));
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn visible_style_messages_redact_remote_urls_and_credentials() {
        let message = "provider https://example.invalid/v1 Authorization Bearer secret-value api_key=secret-value";
        let safe = safe_style_message(message);
        assert!(!safe.contains("example.invalid"));
        assert!(!safe.contains("secret-value"));
        assert!(safe.contains("[REDACTED]"));
    }
}
