[package]
name = "adm-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
adm-ai = { path = "../adm-ai" }
adm-archive = { path = "../adm-archive" }
adm-assets = { path = "../adm-assets" }
adm-config = { path = "../adm-config" }
adm-design = { path = "../adm-design" }
adm-development = { path = "../adm-development" }
adm-foundation = { path = "../adm-foundation" }
adm-packaging = { path = "../adm-packaging" }
adm-pipeline = { path = "../adm-pipeline" }
adm-runtime = { path = "../adm-runtime" }
adm-sdk = { path = "../adm-sdk" }
adm-validation = { path = "../adm-validation" }
serde_json = "1"

[lints]
workspace = true
