[package]
name = "adm4-spec-diff"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "spec_diff"
path = "src/main.rs"

[dependencies]
adm4-spec = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
