[package]
name = "adm-packaging"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
adm-foundation = { path = "../adm-foundation" }
adm-pipeline = { path = "../adm-pipeline" }
adm-validation = { path = "../adm-validation" }

[lints]
workspace = true
